### PR TITLE
Updated Dockerfile base image

### PR DESCRIPTION
**Pull request by A1bert04**
Hello,

I'm submitting this pull request to suggest a change in the Dockerfile base image. Specifically, I propose switching to a more lightweight option, utilizing Alpine Linux instead of Ubuntu.

In my testing, the resulting image size is significantly reduced as follows:                                    
```
> docker images | grep "microocpp"
microocppsim alpine 58f1ddd1fc03 5 seconds ago 392MB
microocppsim ubuntu 431520d7fc4a 3 minutes ago 659MB  
```
I've thoroughly tested this change, and it functions correctly. (Darwin Kernel Version 23.4.0 arm64, MacOs Sonoma 14.4.1 23E224, docker engine v26.0.0)

By adopting a lighter base image, not only will the final build image be smaller, but also it will likely enhance the efficiency of resource utilization and improve overall performance. This change aligns with best practices for containerization, promoting streamlined deployment and management.

Thank you for considering this enhancement.

### CODE REVIEW

**Comment by A1bert04** [comment]
Hello, will this be merged?

Regards,

**Comment by matth-x** [comment]
Hi @A1bert04, thank you for your contribution! Sorry for the delay, I wanted to learn a little bit more about the implications of switching distros. I'm much more familiar with Ubuntu for example and as a development tool, the Simulator should be as simple to use as possible. But I'm certainly not representative for the whole Docker community and don't know if Alpine Linux actually complicates anything in the end. Can we keep this PR open until I find the time to try it? I'm truly amazed by the performance gain!

**Comment by A1bert04** [comment]
No problem for the delay @matth-x .

Typically, when initiating a Docker container that is intended to run a singular service with no many dependencies, such as a Node.js application or a Python server, Alpine Linux is often preferred over Ubuntu or Fedora due to its minimalistic footprint. After the necessary dependencies are installed, the choice of operating system becomes less critical, as the service operates independently and does not rely on additional system tools or resources. 

Let's keep this open looking forward to merge it some day.

Best regards,

**Comment by matth-x** [comment]
Finally found the time to try it. It's a very good fit for the Simulator!

**Pull request merged**
